version: '3'

services:

  nginx:
    build: 
      context: ./nginx
    image: aclima08/nginx
    container_name: nginx
    ports:
      - 8080:80
    depends_on:
      - app-node

  app-node:
    build: 
      context: ./node
    container_name: app-node
    entrypoint: dockerize --wait tcp://database:3306 --timeout 40s docker-entrypoint.sh node index.js
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:  
      - database

  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=database-node
      - MYSQL_ROOT_PASSWORD=root
